# Generated by Django 4.2.6 on 2023-10-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default=2, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='testmodel2',
            name='title',
            field=models.CharField(max_length=50, verbose_name='test Field'),
        ),
    ]
